dirt: 2
stone: 1
coal: 5
lapis_ore: 7
gold_ore: 15
iron_ore: 7
deepSlate: 1
DIAMOND_ORE: 10
REDSTONE_ORE: 3
deepslate_coal_ore: 5
deepslate_iron_ore: 7
deepslate_copper_ore: 2
copper_ore: 2
deepslate_gold_ore: 15
deepslate_redstone_ore: 3
emerald_ore: 10
deepslate_emerald_ore: 10
deepslate_lapis_ore: 7
deepslate_diamond_ore: 10
wood_log: 5